# Generated by Django 4.2.7 on 2023-11-25 21:59

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='Article-Thumbnail/')),
                ('writer', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField()),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('meta_tags', models.TextField()),
                ('meta_description', models.TextField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
