# Generated by Django 4.2.7 on 2023-11-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='description',
        ),
    ]
