# Generated by Django 4.2.7 on 2024-01-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Articles', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Image Gallery', 'verbose_name_plural': 'Image Gallery'},
        ),
    ]
