# Generated by Django 4.2.4 on 2023-11-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('Only Veg', 'Only Veg'), ('Only Non-Veg', 'Only Non-Veg'), ('Both', 'Both')], max_length=20, null=True),
        ),
    ]
