# Generated by Django 4.2.4 on 2023-11-19 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('Only Veg', 'Only Veg'), ('Only Non-Veg', 'Only Non-Veg')], max_length=20, null=True),
        ),
    ]
