# Generated by Django 4.2.7 on 2023-12-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='veg_nonveg',
            field=models.CharField(blank=True, choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], max_length=20, null=True),
        ),
    ]
