# Generated by Django 4.2.7 on 2023-12-17 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_product_veg_nonveg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='veg_nonveg',
            new_name='veg_or_Nonveg',
        ),
    ]
