# Generated by Django 4.2.4 on 2023-11-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations_Reviews_Contact', '0002_reservation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatactUs',
            new_name='ContactUs',
        ),
    ]
