# Generated by Django 4.2.4 on 2023-11-21 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_order_customer_email'),
        ('Product', '0004_alter_product_veg_nonveg'),
        ('Reservations_Reviews_Contact', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.order'),
        ),
        migrations.AlterField(
            model_name='review',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Review-files/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.product'),
        ),
    ]
