# Generated by Django 4.2.7 on 2023-11-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations_Reviews_Contact', '0007_review_order_alter_review_file_alter_review_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('file', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
