# Generated by Django 4.2.7 on 2023-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations_Reviews_Contact', '0010_reservation_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default='Pending', max_length=15),
        ),
    ]
