# Generated by Django 4.2.7 on 2024-01-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations_Reviews_Contact', '0013_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact Us ', 'verbose_name_plural': 'Contact Us '},
        ),
    ]
