# Generated by Django 4.2.4 on 2023-11-19 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_product_veg_nonveg'),
        ('authentication', '0003_remove_address_country_address_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.CharField(blank=True, max_length=400, null=True)),
                ('discount_price', models.FloatField(blank=True, default=0, null=True)),
                ('total', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=400, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=400, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('address_line_1', models.CharField(max_length=400)),
                ('address_line_2', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=400, null=True)),
                ('state', models.CharField(blank=True, max_length=400, null=True)),
                ('postal_code', models.CharField(max_length=400)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Cash On Delivery', 'Cash On Delivery')], default='Pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sub_total', models.FloatField(default=0)),
                ('tax_percentage', models.FloatField(default=0)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=1000000, null=True)),
                ('deliveryCharges', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('order_items', models.ManyToManyField(to='authentication.orderitem')),
            ],
        ),
    ]
