# Generated by Django 4.2.7 on 2024-01-15 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_order_customer_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'orders', 'verbose_name_plural': 'orders'},
        ),
    ]
