# Generated by Django 4.2.7 on 2024-01-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_order_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'Newsletter Subscribers', 'verbose_name_plural': 'Newsletter Subscribers'},
        ),
        migrations.AddField(
            model_name='order',
            name='order_done',
            field=models.BooleanField(default=False),
        ),
    ]
