# Generated by Django 4.2.7 on 2024-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_newsletter_options_order_order_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Pick Up', 'Pick Up'), ('Delivery', 'Delivery')], default='Delivery', max_length=20),
        ),
    ]
