# Generated by Django 5.1.1 on 2024-10-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_giftcarddesigns_remove_giftcard_heading_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedgiftcard",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasedgiftcard",
            name="expire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="purchasedgiftcard",
            name="redeemed",
            field=models.BooleanField(default=False),
        ),
    ]
