# Generated by Django 5.1.1 on 2024-10-10 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0013_purchasedgiftcard_end_date_purchasedgiftcard_expire_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftcarddesigns",
            name="description",
        ),
    ]
