# Generated by Django 5.1.1 on 2024-10-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0015_alter_purchasedgiftcard_gift_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedgiftcard",
            name="code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
