# Generated by Django 5.1.1 on 2024-10-10 20:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_discountcoupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcoupon",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
